linters:
  enable:
    - errcheck
    - govet
    - staticcheck

linters-settings:
  errcheck:
    exclude-functions:
      - (*net.Conn).Close
      - (*net.TCPConn).Close
      - (*net.UnixConn).Close
      - (*os.File).Close
      - (net.Conn).Close
      - (io.Closer).Close

issues:
  exclude-rules:
    # Ignore errcheck in test files for cleanup operations
    - path: _test\.go
      linters:
        - errcheck
